#
# Site settings
#

title: kami

description: kami's blog.

baseurl:

url: http://kami30k.github.io/

#
# Build settings
#

markdown: kramdown

permalink: /posts/:title/

paginate: 1

paginate_path: /posts/page/:num/
