#
# Site settings
#

title: kami's blog

description: kami's blog

baseurl:

# url: http://localhost:4000
url: http://kami30k.com

#
# Build settings
#

markdown: kramdown

permalink: /posts/:title/

paginate: 1

paginate_path: /posts/page/:num/
